"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, MessageCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { GameRoom } from "@/components/games/game-room";

type Sport = "baseball_mlb" | "basketball_nba" | "americanfootball_nfl" | "icehockey_nhl" | "basketball_wnba";
type Event = { id: string; eventName: string; commenceTime: string; awayTeam: string; homeTeam: string; awayScore: number | null; homeScore: number | null; state: "pre" | "in" | "post"; status: string };
const leagues: Array<{ key: Sport; label: string }> = [{ key: "baseball_mlb", label: "MLB" }, { key: "basketball_nba", label: "NBA" }, { key: "americanfootball_nfl", label: "NFL" }, { key: "icehockey_nhl", label: "NHL" }, { key: "basketball_wnba", label: "WNBA" }];
const boardDays = [{ offset: -1, label: "Yesterday" }, { offset: 0, label: "Today" }, { offset: 1, label: "Tomorrow" }];
function scoreboardDate(offset: number) { const date = new Date(); date.setDate(date.getDate() + offset); return `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}${String(date.getDate()).padStart(2, "0")}`; }

export function LeagueScoreboard() {
  const [sport, setSport] = useState<Sport>("baseball_mlb"); const [dayOffset, setDayOffset] = useState(0); const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [openRoom, setOpenRoom] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/games/scoreboard?sport=${sport}&date=${scoreboardDate(dayOffset)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Scoreboard unavailable."); setEvents(data.events ?? []); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Scoreboard unavailable."); } finally { setLoading(false); } }, [dayOffset, sport]);
  useEffect(() => { const first = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, 30_000); return () => { window.clearTimeout(first); window.clearInterval(timer); }; }, [load]);
  return <section className="league-scoreboard"><header><div><Activity /><span><strong>Every game, even without a ticket</strong><small>Public scores for watching and discussion only. STRATIQA locks remain pregame-only.</small></span></div><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "spinning" : ""} /> Refresh</button></header><nav>{leagues.map((league) => <button type="button" className={sport === league.key ? "active" : ""} key={league.key} onClick={() => setSport(league.key)}>{league.label}</button>)}</nav><div className="scoreboard-days">{boardDays.map((day) => <button type="button" className={dayOffset === day.offset ? "active" : ""} key={day.offset} onClick={() => setDayOffset(day.offset)}>{day.label}</button>)}</div>{loading ? <div className="league-scoreboard-loading">Loading public scores…</div> : error ? <div className="league-scoreboard-empty"><ShieldCheck />{error}</div> : events.length ? <div className="league-scoreboard-grid">{events.map((event) => <article key={event.id}><header><span className={event.state}>{event.state === "in" ? "LIVE" : event.state === "post" ? "FINAL" : "SCHEDULED"}</span><small>{event.status}</small></header><div><span><strong>{event.awayTeam}</strong><b>{event.awayScore ?? "–"}</b></span><span><strong>{event.homeTeam}</strong><b>{event.homeScore ?? "–"}</b></span></div><footer><small>{event.state === "pre" ? new Date(event.commenceTime).toLocaleString([], { weekday: "short", hour: "numeric", minute: "2-digit" }) : "Watch-only tracking"}</small><button type="button" onClick={() => setOpenRoom(openRoom === event.id ? "" : event.id)}><MessageCircle /> Game room</button></footer>{openRoom === event.id ? <GameRoom eventId={`espn:${event.id}`} eventName={event.eventName} /> : null}</article>)}</div> : <div className="league-scoreboard-empty"><ShieldCheck />No games are scheduled for this league and day.</div>}</section>;
}
