"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { BrainCircuit, Crown, ShieldCheck, Trophy, Users } from "lucide-react";
import { Badge, Card } from "@/components/ui/primitives";

type Club = { id: string; name: string; description: string; role: "owner" | "member"; roster: Array<{ role: string; alias: string; slug: string | null; rating: number; verified: number }>; performance: { rating: number; verified: number; wins: number; losses: number } };
type Invite = { id: string; model_clubs?: { name: string; description: string } };

export function ModelClubs() {
  const [clubs, setClubs] = useState<Club[]>([]); const [invites, setInvites] = useState<Invite[]>([]); const [loading, setLoading] = useState(true); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [inviteSlug, setInviteSlug] = useState<Record<string, string>>({}); const [status, setStatus] = useState("");
  const refresh = () => fetch("/api/clubs", { cache: "no-store" }).then((response) => response.ok ? response.json() : { clubs: [], invites: [] }).then((data) => { setClubs(data.clubs ?? []); setInvites(data.invites ?? []); }).finally(() => setLoading(false));
  useEffect(() => { void refresh(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setStatus("Creating club..."); const response = await fetch("/api/clubs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description }) }); const result = await response.json(); if (!response.ok) return setStatus(result.error); setName(""); setDescription(""); setStatus("Club created. Your verified record is now its foundation."); await refresh(); }
  async function accept(inviteId: string) { setStatus("Joining club..."); const response = await fetch("/api/clubs/invites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ inviteId }) }); const result = await response.json(); setStatus(response.ok ? "Club invite accepted." : result.error); if (response.ok) await refresh(); }
  async function invite(clubId: string) { const slug = inviteSlug[clubId]?.trim(); if (!slug) return; setStatus("Sending invite..."); const response = await fetch("/api/clubs/invites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clubId, slug }) }); const result = await response.json(); setStatus(response.ok ? "Invite sent." : result.error); if (response.ok) setInviteSlug((current) => ({ ...current, [clubId]: "" })); }
  return <div className="product-page clubs-page"><header className="product-hero"><div><Badge tone="accent"><Users size={11} /> MODEL CLUBS</Badge><h1>Build a sharper room.</h1><p>Private clubs bring trusted analysts together around verified results. Members keep their picks and model strategy private; the club only sees the aggregate record.</p></div></header>
    <section className="clubs-intro"><Card><Crown /><span><strong>Ratings stay personal</strong><p>Your category rating belongs to you. Club scores are a separate, shared snapshot.</p></span></Card><Card><ShieldCheck /><span><strong>Proof over claims</strong><p>Only automatically settled STRATIQA results build the club record.</p></span></Card><Card><BrainCircuit /><span><strong>Models stay private</strong><p>No club member can see another analyst&apos;s weights, notes, or recommendations.</p></span></Card></section>
    {invites.length ? <section className="club-invites"><header><Users /><span><strong>Club invites</strong><small>Accepting adds your aggregate record to the club.</small></span></header>{invites.map((invite) => <article key={invite.id}><span><strong>{invite.model_clubs?.name ?? "Private club"}</strong><small>{invite.model_clubs?.description || "A private room for verified analysts."}</small></span><button onClick={() => void accept(invite.id)}>Accept invite</button></article>)}</section> : null}
    <section className="clubs-layout"><Card className="club-create"><header><Trophy /><span><strong>Start a club</strong><small>Create a private circle for your best analysts.</small></span></header><form onSubmit={create}><label>Club name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Sunday Slate Society" maxLength={48} required /></label><label>What is this club about?<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Props specialists building a better process." maxLength={180} /></label><button className="button" type="submit">Create private club</button></form></Card><div className="club-list">{loading ? <Card className="premium-empty"><strong>Loading your clubs...</strong></Card> : clubs.length ? clubs.map((club) => <Card className="club-card" key={club.id}><header><span><Users /><strong>{club.name}</strong><small>{club.role === "owner" ? "You founded this club" : "Member"}</small></span><Badge tone="accent">{club.roster.length} MEMBERS</Badge></header><p>{club.description || "A private room built around verified improvement."}</p><div className="club-score"><span><small>CLUB RATING</small><strong>{club.performance.rating}</strong></span><span><small>VERIFIED</small><strong>{club.performance.verified}</strong></span><span><small>RECORD</small><strong>{club.performance.wins}-{club.performance.losses}</strong></span></div><footer>{club.roster.map((member) => <span key={`${club.id}-${member.alias}`}><i>{member.alias.slice(0, 1).toUpperCase()}</i><b>{member.slug ? <Link href={`/analysts/${member.slug}`}>{member.alias}</Link> : member.alias}</b><small>{member.rating} · {member.verified} verified</small></span>)}</footer>{club.role === "owner" ? <div className="club-invite-form"><input value={inviteSlug[club.id] ?? ""} onChange={(event) => setInviteSlug((current) => ({ ...current, [club.id]: event.target.value }))} placeholder="Analyst public slug" /><button onClick={() => void invite(club.id)}>Invite analyst</button></div> : null}</Card>) : <Card className="premium-empty"><Users /><strong>Your first club is waiting.</strong><p>Create a focused room for analysts you trust.</p></Card>}</div></section>{status ? <p className="ledger-status">{status}</p> : null}
  </div>;
}
