alter table public.analyst_models
  add column if not exists strategy text not null default 'balanced',
  add column if not exists risk_profile text not null default 'balanced'
    check (risk_profile in ('selective', 'balanced', 'opportunistic')),
  add column if not exists weights jsonb not null default '{}'::jsonb;

alter table public.graded_betting_activity
  add column if not exists model_id uuid references public.analyst_models(id) on delete set null;

update public.graded_betting_activity activity
set model_id = model.id,
    pick_origin = 'model'
from public.analyst_models model
where activity.attribution_type = 'model'
  and activity.model_id is null
  and activity.user_id = model.user_id
  and lower(activity.model_name) = lower(model.name);

update public.graded_betting_activity
set attribution_type = 'judgment',
    model_name = null,
    pick_origin = 'personal'
where attribution_type = 'model'
  and model_id is null;

create index if not exists graded_activity_model_performance_idx
on public.graded_betting_activity (model_id, verification_status, result)
where model_id is not null;

alter table public.graded_betting_activity
  drop constraint if exists model_attribution_requires_identity;

alter table public.graded_betting_activity
  add constraint model_attribution_requires_identity check (
    attribution_type <> 'model'
    or (
      model_id is not null
      and nullif(trim(model_name), '') is not null
      and pick_origin = 'model'
    )
  );

comment on column public.graded_betting_activity.model_id is
'Immutable owner-validated model identity captured when a provider-linked pick is locked.';

comment on column public.analyst_models.weights is
'Factor emphasis generated by the guided builder. Advanced controls may edit these values later.';

create or replace function public.enforce_owned_model_attribution()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.model_id is not null and not exists (
    select 1 from public.analyst_models
    where id = new.model_id and user_id = new.user_id and status <> 'retired'
  ) then
    raise exception 'Model attribution must reference an active model owned by the pick owner';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_owned_model_on_pick on public.graded_betting_activity;
create trigger enforce_owned_model_on_pick
before insert or update of model_id, user_id on public.graded_betting_activity
for each row execute function public.enforce_owned_model_attribution();
